### ISSUE TITLE
Create Game Blank Screen

### ISSUE THREAD

**Issue by ptmuldoon** [buttons-against-humanity/bah-frontend#6]
This is likely my own user error as not being very familiar with docker just yet.   But when I attempt to create a game, I am presented with a blank screen.   And similar, when I press on 'cockpit' in the top, I also receive a blank screen.

My main steps were to git clone the front and back ends, create an .env file and docker compose up.
Then within portainer, I have restart each container assigning the ports.
I can then access the front end.  But attempts to create a game gives a blank screen.

Again, I assume this my own errors, but not sure where or what steps I may be doing incorrectly.

And any help is greatly appreciated.
Thank you

**Comment by macno** [comment]
Hi, would you try to add:

```
COCKPIT_URL=https://buttons-against-humanity.github.io/decks/full.json
```

To the .env file and execute `docker-compose up -d` ?

**Comment by ptmuldoon** [comment]
@macno.

Thanks for trying to help me out, and still suspect just my setup or stupidity with docker.   I'm trying with Alpine Linux and may try with Ubuntu or Debian to see if maybe some dependency is missing. I do have Java11 installed in Alpine.

I changed the COCKPIT_URL to the above but still get the same result after restarting docker-compose up.    The front end starts.  When I press join a game, I get the pop up option to enter a game ID.   But pressing create a game or cockpit just gives me a blank screen.   

My full .env file is:

```
PORT=8080
LOG_LEVEL=debug

RESTART_MODE=unless-stopped
FQDN=localhost

#COCKPIT_URL=https://github.com/macno/json-against-humanity/raw/full-json/decks/family.json
#COCKPIT_URL=https://github.com/macno/json-against-humanity/raw/full-json/decks/full.json
COCKPIT_URL=https://buttons-against-humanity.github.io/decks/full.json
SLACKIN_URL=https://slack.buttonsagainsthumanity.com/

# Used to force a COCKPIT reload via API, it's sha256 (Authorization: Bearar secrett+ttoken)
ADMIN_TOKEN=514a1cd20c03cd8a234dca0fddb87cf53a26bb7b2a66e2aae62a0a544237f96b

# Set MULTI_NODE to 1 to enable support for replicas
# It requires a redis instance available
MULTI_NODE=0
STICKY_COOKIE=bah-sticky
REDIS_HOST=cache
REDIS_PORT=6379
REDIS_OPTS={"socket_keepalive":false}
```

**Comment by macno** [comment]
could you paste the output of `docker-compose logs be`  ?

**Comment by ptmuldoon** [comment]
It looks like the server may not be starting?

```
adocker:~/bah-backend# docker-compose logs be
Attaching to bah-backend_be_1
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:40.293Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:41.512Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:42.680Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:44.100Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:45.884Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:53.870Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:55.170Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:56.460Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:57.877Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:33:59.667Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:34:02.311Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:34:06.525Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:34:13.976Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:34:27.803Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:34:54.424Z","v":0}
be_1       | {"name":"bah","hostname":"3e86d9ec071c","pid":1,"level":50,"msg":"Unable to start server cards.forEach is not a function","time":"2020-07-09T16:35:47.540Z","v":0}
```

**Comment by macno** [comment]
I'm sorry, the latest images have some bugs. They have been already fixed, could you update your docker-compose.yaml to use these images:   

```
  be:
    image: buttonsagainsthumanity/bah-backend:0.11.0-beta.0
  fe:
    image: buttonsagainsthumanity/bah-frontend:0.9.0-beta.0
```

Meanwhile I already pushed a new tag, so once the images are build and published you can switch back to use latests

Sorry about that

**Comment by macno** [comment]
Images published

**Comment by ptmuldoon** [comment]
Well, I changed my docker-compose to use the beta images. and log shows "Attaching to bah-backend_be_1" with no errors.

But still stuck on that blank screen when creating a game.    I thinking it must be something I am doing and not the game or code, just can't figure it out.   I've tried with Alpine Linux and Ubuntu Server installs.  Docker compose up gets things goings, and then i am using Portainer to publish all the ports.    

And I can access the front screen, just get that darn blank screen when pressing "create game" or "explore all extensions"

And accessing the back end appears be running and shows in a web browser:
{"name":"bah-backend","version":"0.11.0-beta.0"}  

And my .env file is using the Cockpit url of:
COCKPIT_URL=https://buttons-against-humanity.github.io/decks/full.json

I must be missing something, probably a very easy thing I'm just doing incorrectly.

**Comment by macno** [comment]
if you open the browser's console, do you see any error? Which URL are you using in your browser `http://localhost`?

**Comment by ptmuldoon** [comment]
EDIT.  You can ignore most of the below.  I got it work.

I found I needed to change the FGDN to point to the VM's IP and not to localhost.
And think the server error below is that the env.sample file has a small typo on the Cockpit url that I missed earlier.

COCKPIT_URL=COCKPIT_URL=https://buttons-against-humanity.github.io/decks/full.json

I'm doing everything inside a VM using proxmox as my baremetal hypervisor, which may or may not be part of the issue.   So I do not visit http://localhost, but rather the IP address of the VM.   And VM's are running Alpine Linux and Ubuntu Server with no GUIs.   

Should we be accessing it directly on the IP address at port 80?  ie, 192.168.xx.xx?   I just did a clean install of Ubuntu Server (as a VM) with no other dockers installed and latest docker images.  When I ran compose-up:

When I visit the VM IP address in the web browser, I get 404 page not found error.
and the compose-docker logs be shows an error of:

```
Attaching to bah-backend_be_1
be_1       | {"name":"bah","hostname":"69fdb7a89b1f","pid":1,"level":50,"msg":"Unable to start server Only absolute URLs are supported","time":"2020-07-10T13:26:24.364Z","v":0}
```

On my previous attempts, I have had the Portainer docker installed first, and then after running compose-up via CLI for buttons, went back to portainer (port 9000) and assigned the FE and BE specific ports to publish to ports 80 and 8080.   I could then in a browser open the game that directed to port 8080 with something like.  192.168.xx.xx:32768   where 32768 was publishing the port to 8080 for the FE container.   But was still stuck at a blank screen when trying to create a game.

And thank you for all of you help.  You have gone above and beyond in attempting to help me trouble shoot.  If you have any kind of donation link for the game, I would be more than happy to make a donation.

**Comment by macno** [comment]
Did you remove traefik from the docker-compose.yaml ? It supposed to be there since it proxies the requests to the BE and FE containers (their ports are not exposed).  
if the port 80 is already busy, you can change it to 8080, for example:
```
  traefik:
    image: traefik:v2.2
    restart: ${RESTART_MODE}
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
```

About the donation, thank you but please donate to a charity of your choice !
